In [ ]:
#@title Twitter Auth Token

twitter_auth_token = '4e9c9cd9ee288b80454f5f2526390f3e008f5752' # change this auth token

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,110 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,615 kB]
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,701 kB]
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,453 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,487 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,425 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,164 kB]
Fetched 20.4 MB in 3s (7,448 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.18).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Get:9 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [9,431 B]
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 21.6 kB in 1s (14.9 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 55 not upgraded.
Need to get 31.8 MB of archives.
After this operation, 197 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.18.0-1nodesource1 [31.8 MB]
Fetched 31.8 MB in 1s (59.6 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 123629 files and directories currently installed.)
Preparing to unpack .../nodejs_20.18.0-1nodesource1_amd64.deb ...
Unpacking nodejs (20.18.0-1nodesource1) ...
Setting up nodejs (20.18.0-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.18.0

In [ ]:
# Crawl Data

filename = 'tweet_depresi2.csv'
search_keyword = 'depresi OR bersalah OR nyerah OR stres OR gagal lang:id until:2024-11-12 since:2024-10-01'
limit = 2500

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/tweet_depresi1.csv, renaming to ./tweets-data/tweet_depresi1.old.csv

-- Scrolling... (1)
Filling in keywords: depresi (depresi) lang:id until:2024-11-12 since:2024-10-01

[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@7493bc3b151ff71d7345f7713b82495f"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error: page.waitForTimeout: Target page, context or browser has been closed
Keywords: depresi (depresi) lang:id until:2024-11-12 since:2024-10-01
Twitter Harvest v 2.6.1
^C

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1857568752931582343,Fri Nov 15 23:37:57 +0000 2024,5,aku kira belakangan ini aku depresi trnyta aku...,1857568752931582343,https://pbs.twimg.com/media/Gcdo7xyaIAAh7C9.jpg,NaN,in,mossy bottom,0,1,0,https://x.com/greenforgy/status/18575687529315...,1597537702223970305,greenforgy
1,1857568501600514110,Fri Nov 15 23:36:57 +0000 2024,0,aku sedih pdhl lg pgn di support,1857568501600514110,NaN,NaN,in,NaN,0,0,0,https://x.com/sparklespinkie/status/1857568501...,1328651617390903300,sparklespinkie
2,1857473774918176885,Fri Nov 15 23:36:39 +0000 2024,0,@mochicherryyy WAKAKAKKAK,1857568427361341746,NaN,mochicherryyy,in,caratland 💎,0,0,0,https://x.com/depres0t/status/1857568427361341746,4399128134,depres0t
3,1857567809565606274,Fri Nov 15 23:34:12 +0000 2024,0,hari ini aku diklat,1857567809565606274,NaN,NaN,in,NaN,0,0,0,https://x.com/sparklespinkie/status/1857567809...,1328651617390903300,sparklespinkie
4,1857567710424781288,Fri Nov 15 23:33:50 +0000 2024,3,1. Mengurangi Risiko Depresi Pemikiran yang po...,1857567718679142769,NaN,quoterandom05,in,NaN,0,1,0,https://x.com/quoterandom05/status/18575677186...,1734143539226001408,quoterandom05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,1856679289594564934,Wed Nov 13 15:09:58 +0000 2024,0,@hotrachasauce Jejangan dia meninggoy gegara d...,1856716139528868195,NaN,hotrachasauce,in,NaN,0,1,0,https://x.com/hyn_hwng/status/1856716139528868195,1480790411580882945,hyn_hwng
464,1856707029521609156,Wed Nov 13 15:09:12 +0000 2024,0,@Phillatheria Keadaan yang tidak memunhkinkan ...,1856715946939068445,NaN,Phillatheria,in,NaN,0,0,0,https://x.com/Fiokazz/status/1856715946939068445,1288672703860191232,Fiokazz
465,1856706543796023365,Wed Nov 13 15:07:39 +0000 2024,23,@kacamatahakim Di cari bro kebenarannya jangan...,1856715555891454172,NaN,kacamatahakim,in,NaN,0,1,0,https://x.com/Fiokazz/status/1856715555891454172,1288672703860191232,Fiokazz
466,1856715375096070230,Wed Nov 13 15:06:56 +0000 2024,0,Siapapun beliin gue bebek madura rica rica pin...,1856715375096070230,NaN,NaN,in,NaN,0,0,0,https://x.com/briefinquery/status/185671537509...,1410154474945925120,briefinquery
467,1856712876989501559,Wed Nov 13 15:05:29 +0000 2024,0,@iteramfs Gk usah kkn nder nanti rame2 bilang ...,1856715012565610598,NaN,iteramfs,in,| ☕🎹 | ⭐💧 | 🎈🤖 |,0,0,0,https://x.com/kudemana/status/1856715012565610598,1262553690293977088,kudemana

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 468.

In [ ]:
df.to_csv('/content/drive/MyDrive/SKRIPSI/tweet_depresi1.csv', index=False)

In [ ]:
!pip install --upgrade snscrape
import snscrape.modules.twitter as sntwitter
import pandas as pd
import time

# Query untuk mencari tweet dengan kata-kata terkait depresi (Bahasa Indonesia)
query = "depresi OR bersalah OR stres OR cemas OR diabaikan OR dikucilkan OR frustasi OR gagal OR galau OR gelisah OR hampa OR kecewa OR kesepian OR menyerah OR sedih OR sendirian OR terasing OR terpuruk OR pasrah OR lelah lang:id since:2024-01-01 until:2025-01-01"
tweets = []

# Looping untuk mengambil tweet
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
    try:
        if i >= 5000:  # Batasi jumlah tweet hingga 5000
            break
        if tweet is not None:  # Hindari error jika tweet kosong
            tweets.append([tweet.date, tweet.user.username, tweet.content])

        # Tunggu sebentar agar tidak terdeteksi sebagai spam
        time.sleep(2)  # Bisa diatur sesuai kebutuhan
    except Exception as e:
        print(f"Error saat scraping tweet ke-{i}: {e}")
        continue  # Lanjutkan ke iterasi berikutnya jika ada error

# Simpan hasil dalam DataFrame
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])

# Simpan ke Google Drive atau penyimpanan lokal
df.to_csv('/content/drive/MyDrive/SKRIPSI/tweet_depresi2.csv', index=False, encoding='utf-8')

Requirement already satisfied: snscrape in /usr/local/lib/python3.11/dist-packages (0.7.0.20230622)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from snscrape) (2.32.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from snscrape) (5.3.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from snscrape) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from snscrape) (3.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->snscrape) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->snscrape) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (2025.1.31)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (1.7.1)

ERROR:snscrape.base:Error retrieving https://twitter.com/search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"))
CRITICAL:snscrape.base:4 requests to https://twitter.com/search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click failed, giving up.
CRITICAL:snscrape.base:Errors: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))")), SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))")), SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))")), SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"))

ScraperException: 4 requests to https://twitter.com/search?f=live&lang=en&q=depresi+OR+bersalah+OR+stres+OR+cemas+OR+diabaikan+OR+dikucilkan+OR+frustasi+OR+gagal+OR+galau+OR+gelisah+OR+hampa+OR+kecewa+OR+kesepian+OR+menyerah+OR+sedih+OR+sendirian+OR+terasing+OR+terpuruk+OR+pasrah+OR+lelah+lang%3Aid+since%3A2024-01-01+until%3A2025-01-01&src=spelling_expansion_revert_click failed, giving up.

In [ ]:
!pip install --upgrade snscrape
import snscrape.modules.twitter as sntwitter
import pandas as pd
import time

# Query untuk mencari tweet dengan kata-kata terkait depresi (Bahasa Indonesia)
query = "cape hidup OR nyerah lang:id since:2024-10-01 until:2025-01-01"
tweets = []

# Looping untuk mengambil tweet
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
    try:
        if i >= 5000:  # Batasi jumlah tweet hingga 5000
            break
        if tweet is not None:  # Hindari error jika tweet kosong
            tweets.append([tweet.date, tweet.user.username, tweet.content])

        # Tunggu sebentar agar tidak terdeteksi sebagai spam
        time.sleep(2)  # Bisa diatur sesuai kebutuhan
    except Exception as e:
        print(f"Error saat scraping tweet ke-{i}: {e}")
        continue  # Lanjutkan ke iterasi berikutnya jika ada error

# Simpan hasil dalam DataFrame
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])

# Simpan ke Google Drive atau penyimpanan lokal
df.to_csv('/content/tweetdep2.csv', index=False, encoding='utf-8')

In [ ]:
twitter_auth_token = "4e9c9cd9ee288b80454f5f2526390f3e008f5752"

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,927 kB]
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,901 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,546 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,211 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,245 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,722 kB]
Fetched 20.9 MB in 4s (5,211 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.20).
gnupg is already the newest version (2.2.27-3ubuntu2.3).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Get:4 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [11.0 kB]
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 23.1 kB in 2s (15.2 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 35 not upgraded.
Need to get 32.0 MB of archives.
After this operation, 199 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.19.1-1nodesource1 [32.0 MB]
Fetched 32.0 MB in 1s (50.1 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 126102 files and directories currently installed.)
Preparing to unpack .../nodejs_20.19.1-1nodesource1_amd64.deb ...
Unpacking nodejs (20.19.1-1nodesource1) ...
Setting up nodejs (20.19.1-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.19.1

In [ ]:
# Crawl Data
filename = "tweetdep1.csv"
search_keyword = "nyerah OR nyerah hidup OR capek hidup OR capek OR bunuh diri OR bundir lang:id since:2024-05-01 until:2025-09-30"
limit = 2000

!npx --yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/tweetdep1.csv, renaming to ./tweets-data/tweetdep1.old.csv

Filling in keywords: nyerah OR nyerah hidup OR capek hidup OR capek OR bunuh diri OR bundir lang:id since:2024-05-01 until:2025-09-30


-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 14


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 33

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 48

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 67

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 85

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 102

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 118

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 134

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 151

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 166

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 185

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 202

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 216

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 234


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 250

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 269

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 284

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 302

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 317

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 334


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 351

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 369

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 387

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 403

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 419

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 434

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 451

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 468

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 484

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 501


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 516

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 530

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 548


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 565

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 582

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 601

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 613

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 631

--Taking a break, waiting for 10 seconds...
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@3f3fcf0fc259cb3aa25b06b26d6bb23c"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@fdd91ab674e1cf0052c32d24ea3faa3e"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@5a68ab51b72490fa5d76c811ddfd7c27"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@994c627b095615440a377ec3b6b7ebd3"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@9235500cbc54e1156a096db95ccb7da4"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@8587072c41dda5794b29b03aa9e04cfd"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@3e15d4f4b5080c90eaa6d5e497f53486"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@243f00bc219635fc31ce4d2f18fd1cff"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@dde5d33c0c2a6da367bc4db8a6f50ceb"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@ba9893cc9857e13bfb9df9bc0605abd8"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@1b0e3fbf756eee7d5eb2da7224c6360f"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 644


Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 659

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 675

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 693

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 708

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 725

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/tweetdep1.csv
Total tweets saved: 739

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 739 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1921958605235925040,Mon May 12 16:00:16 +0000 2025,0,gua nyerah. rasanya udah gamau peduli lagi apa...,1921958613473497405,NaN,mrezamartin,in,Jakarta Capital Region,0,0,0,https://x.com/mrezamartin/status/1921958613473...,1139834235840188416,mrezamartin
1,1921599858814709985,Sun May 11 16:14:42 +0000 2025,0,its okeeey je 2 tahun biasanya sendiri kan gap...,1921599858814709985,NaN,NaN,in,NaN,0,0,0,https://x.com/vvidianka/status/192159985881470...,1218928482127736832,vvidianka
2,1921465903926936035,Sun May 11 15:02:55 +0000 2025,0,@AdamSyahaha apapun keadaannya tetep nguatin d...,1921581792034758794,NaN,AdamSyahaha,in,ca-pek cuy,0,0,0,https://x.com/_172jt/status/1921581792034758794,2758973146,_172jt
3,1921161056786817066,Sat May 10 13:45:25 +0000 2025,0,@terasnongki Ges inget semua masalah itu ada j...,1921199902807261571,NaN,terasnongki,in,𝐂𝐍𝐃-SND-ILTB-2,0,1,0,https://x.com/hecahna/status/1921199902807261571,2348815189,hecahna
4,1921002154933801271,Sat May 10 00:39:38 +0000 2025,0,Rasanya nyerah banget ga nyaman jalanin hidup ...,1921002154933801271,NaN,NaN,in,STRICTLY DON'T FOLLOW!,0,0,0,https://x.com/bachiraor/status/192100215493380...,1846096983905468416,bachiraor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,1787126203037646853,Sun May 05 14:24:25 +0000 2024,0,Krn gk sekedar ngelawan orang2 jahat modelan l...,1787126205801808230,NaN,who_buttercup,in,NaN,0,1,0,https://x.com/who_buttercup/status/17871262058...,1313455544829505537,who_buttercup
735,1786959287300030623,Sun May 05 03:21:08 +0000 2024,0,Jujur sejauh ini kalo di posisi S kayanya gua ...,1786959287300030623,NaN,NaN,in,NaN,0,0,0,https://x.com/Zuzuzee_/status/1786959287300030623,1676604022042574851,Zuzuzee_
736,1786796644522205393,Sat May 04 16:34:53 +0000 2024,0,Harus hidup dengan damai sampai tua malah hamp...,1786796650968891523,NaN,ikanemoss,in,NaN,0,0,0,https://x.com/ikanemoss/status/178679665096889...,1609961842461540352,ikanemoss
737,1786641935253537222,Sat May 04 06:26:51 +0000 2024,0,@ssefnum 5 antara semangat hidup dan nyerah hi...,1786643635330818074,NaN,ssefnum,in,NaN,0,0,0,https://x.com/_kkith/status/1786643635330818074,1619840861474541569,_kkith
738,1786620073366757485,Sat May 04 04:53:13 +0000 2024,0,Drama bgt udh maju mundur mau konseling. Tapi ...,1786620073366757485,NaN,NaN,in,NaN,0,0,0,https://x.com/sarcasticbtches/status/178662007...,1135206523959799808,sarcasticbtches

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.to_csv('/content/tweetdep3.csv', index=False)

# df.to_csv('/content/drive/MyDrive/SKRIPSI/tweet_depresi3.csv', index=False)

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 2003.

In [ ]:
# Install snscrape
!pip install --upgrade snscrape

# Import libraries
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Query pencarian tweet dengan kata-kata yang berkaitan dengan depresi (bahasa Indonesia)
# query = '(depresi OR bersalah OR stres OR cemas OR diabaikan OR dikucilkan OR frustasi OR gagal OR galau OR gelisah OR hampa OR kecewa OR kesepian OR menyerah OR sedih OR sendirian OR terasing OR terpuruk OR pasrah OR lelah OR terluka) lang:id since:2025-01-01 until:2025-01-02'
query = 'depresi lang:id since:2025-01-01 until:2025-01-02'
limit = 1000
%time

# Menyimpan tweet ke dalam list
tweets = []
try:
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()): # Changed to include index 'i' in the loop
    if len(tweets) == limit:
      break
    else:
      tweets.append([tweet.date, tweet.user.username, tweet.content])
  # Create DataFrame outside the loop to ensure it's defined
  df = pd.DataFrame(tweets, columns=['date', 'username', 'tweet'])

except Exception as e:
  print(e)

# Simpan ke file CSV
df.to_csv('/content/tweet_dep.csv', index=False, encoding='utf-8')

# Tampilkan 5 data pertama untuk memastikan
df.head()

Collecting snscrape
  Downloading snscrape-0.7.0.20230622-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from snscrape) (2.32.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from snscrape) (5.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from snscrape) (4.13.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from snscrape) (3.18.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->snscrape) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->snscrape) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (2025.4.26)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->snscrape) (1.7.1)
Downloading snscrape-0.7.0.20230622-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 2.0 MB/s eta 0:00:00
Installing collected packages: snscrape
Successfully installed snscrape-0.7.0.20230622

KeyboardInterrupt: