In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 7.5 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1

In [ ]:
import pandas as pd
import emoji
import re

# import seaborn as sns
# import matplotlib.pyplot as plt
# import nltk

DATA KOTOR

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/SKRIPSI/New/a_label_dep.csv", encoding='latin1')
df

,conversation_id_str,created_at,favorite_count,label,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1.860000e+18,Fri Nov 15 23:36:57 +0000 2024,0,depresi,aku sedih pdhl lg pgn di support,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.860000e+18,Fri Nov 15 23:36:39 +0000 2024,0,normal,@muh_basra Keknya beban depresi pada cash for ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.890000e+18,Fri Jan 31 23:51:35 +0000 2025,1,depresi,gue udah di titik cape banget nutup nutupin im...,1.890000e+18,NaN,NaN,in,NaN,0.0,1.0,0,https://x.com/babajiie/status/1885476051121561889,1.68E+18,babajiie
3,1.890000e+18,Fri Jan 31 23:30:44 +0000 2025,0,depresi,Kadang pengen gw ledakin tapi takut ada yg nyi...,1.890000e+18,NaN,NaN,in,Seven heaven,0.0,0.0,0,https://x.com/gadiskostan/status/1885470803027...,1.68E+18,gadiskostan
4,1.890000e+18,Fri Jan 31 23:27:21 +0000 2025,4,normal,Rasa bersalah juga kalau jumpa mashayikh tak c...,1.890000e+18,NaN,NaN,in,NaN,0.0,0.0,0,https://x.com/musaddad00/status/18854699505732...,1.78E+18,musaddad00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1.860000e+18,Wed Oct 23 15:28:50 +0000 2024,0,depresi,Hari demi hari makin di bikin takut buat ngela...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,1.860000e+18,Wed Oct 23 15:19:03 +0000 2024,0,depresi,nyerah aja kali ya beneran capek sm kehidupan ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,1.860000e+18,Wed Oct 23 15:15:21 +0000 2024,0,normal,@diddekarisma Udah nyerah sama hidup tuh makan...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,1.860000e+18,Wed Oct 23 15:15:05 +0000 2024,0,depresi,udah di tahap nyerah sm diri sendiri nyoba bua...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,1.860000e+18,Wed Oct 23 15:14:54 +0000 2024,0,normal,@iteramfs Gk usah kkn nder nanti rame2 bilang ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Ambil 5 data paling awal dan 5 data terakhir
df_first_5 = df.head(5)  # Ambil 5 data pertama
df_last_5 = df.tail(5)   # Ambil 5 data terakhir

# Gabungkan hasilnya untuk menampilkan
df_combined = pd.concat([df_first_5, df_last_5])

# Tampilkan hasilnya
print("5 Data Paling Awal dan 5 Data Terakhir:")
print(df_combined)

# Cek bentuk DataFrame setelah slicing
print("Shape setelah slicing:", df_combined.shape)

5 Data Paling Awal dan 5 Data Terakhir:
      conversation_id_str                      created_at  favorite_count  \
0            1.860000e+18  Fri Nov 15 23:36:57 +0000 2024               0
1            1.860000e+18  Fri Nov 15 23:36:39 +0000 2024               0
2            1.890000e+18  Fri Jan 31 23:51:35 +0000 2025               1
3            1.890000e+18  Fri Jan 31 23:30:44 +0000 2025               0
4            1.890000e+18  Fri Jan 31 23:27:21 +0000 2025               4
4995         1.860000e+18  Wed Oct 23 15:28:50 +0000 2024               0
4996         1.860000e+18  Wed Oct 23 15:19:03 +0000 2024               0
4997         1.860000e+18  Wed Oct 23 15:15:21 +0000 2024               0
4998         1.860000e+18  Wed Oct 23 15:15:05 +0000 2024               0
4999         1.860000e+18  Wed Oct 23 15:14:54 +0000 2024               0

        label                                          full_text  \
0     depresi                   aku sedih pdhl lg pgn di support
1      normal  @muh_basra Keknya beban depresi pada cash for ...
2     depresi  gue udah di titik cape banget nutup nutupin im...
3     depresi  Kadang pengen gw ledakin tapi takut ada yg nyi...
4      normal  Rasa bersalah juga kalau jumpa mashayikh tak c...
4995  depresi  Hari demi hari makin di bikin takut buat ngela...
4996  depresi  nyerah aja kali ya beneran capek sm kehidupan ...
4997   normal  @diddekarisma Udah nyerah sama hidup tuh makan...
4998  depresi  udah di tahap nyerah sm diri sendiri nyoba bua...
4999   normal  @iteramfs Gk usah kkn nder nanti rame2 bilang ...

            id_str image_url in_reply_to_screen_name lang      location  \
0     1.860000e+18       NaN                     NaN  NaN           NaN
1     1.860000e+18       NaN                     NaN  NaN           NaN
2     1.890000e+18       NaN                     NaN   in           NaN
3     1.890000e+18       NaN                     NaN   in  Seven heaven
4     1.890000e+18       NaN                     NaN   in           NaN
4995  1.860000e+18       NaN                     NaN  NaN           NaN
4996  1.860000e+18       NaN                     NaN  NaN           NaN
4997  1.860000e+18       NaN                     NaN  NaN           NaN
4998  1.860000e+18       NaN                     NaN  NaN           NaN
4999  1.860000e+18       NaN                     NaN  NaN           NaN

      quote_count  reply_count retweet_count  \
0             NaN          NaN           NaN
1             NaN          NaN           NaN
2             0.0          1.0             0
3             0.0          0.0             0
4             0.0          0.0             0
4995          NaN          NaN           NaN
4996          NaN          NaN           NaN
4997          NaN          NaN           NaN
4998          NaN          NaN           NaN
4999          NaN          NaN           NaN

                                              tweet_url user_id_str  \
0                                                   NaN         NaN
1                                                   NaN         NaN
2     https://x.com/babajiie/status/1885476051121561889    1.68E+18
3     https://x.com/gadiskostan/status/1885470803027...    1.68E+18
4     https://x.com/musaddad00/status/18854699505732...    1.78E+18
4995                                                NaN         NaN
4996                                                NaN         NaN
4997                                                NaN         NaN
4998                                                NaN         NaN
4999                                                NaN         NaN

         username
0             NaN
1             NaN
2        babajiie
3     gadiskostan
4      musaddad00
4995          NaN
4996          NaN
4997          NaN
4998          NaN
4999          NaN
Shape setelah slicing: (10, 16)

In [ ]:
df_combined

,conversation_id_str,created_at,favorite_count,label,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1.860000e+18,Fri Nov 15 23:36:57 +0000 2024,0,depresi,aku sedih pdhl lg pgn di support,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.860000e+18,Fri Nov 15 23:36:39 +0000 2024,0,normal,@muh_basra Keknya beban depresi pada cash for ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.890000e+18,Fri Jan 31 23:51:35 +0000 2025,1,depresi,gue udah di titik cape banget nutup nutupin im...,1.890000e+18,NaN,NaN,in,NaN,0.0,1.0,0,https://x.com/babajiie/status/1885476051121561889,1.68E+18,babajiie
3,1.890000e+18,Fri Jan 31 23:30:44 +0000 2025,0,depresi,Kadang pengen gw ledakin tapi takut ada yg nyi...,1.890000e+18,NaN,NaN,in,Seven heaven,0.0,0.0,0,https://x.com/gadiskostan/status/1885470803027...,1.68E+18,gadiskostan
4,1.890000e+18,Fri Jan 31 23:27:21 +0000 2025,4,normal,Rasa bersalah juga kalau jumpa mashayikh tak c...,1.890000e+18,NaN,NaN,in,NaN,0.0,0.0,0,https://x.com/musaddad00/status/18854699505732...,1.78E+18,musaddad00
4995,1.860000e+18,Wed Oct 23 15:28:50 +0000 2024,0,depresi,Hari demi hari makin di bikin takut buat ngela...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,1.860000e+18,Wed Oct 23 15:19:03 +0000 2024,0,depresi,nyerah aja kali ya beneran capek sm kehidupan ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,1.860000e+18,Wed Oct 23 15:15:21 +0000 2024,0,normal,@diddekarisma Udah nyerah sama hidup tuh makan...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,1.860000e+18,Wed Oct 23 15:15:05 +0000 2024,0,depresi,udah di tahap nyerah sm diri sendiri nyoba bua...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,1.860000e+18,Wed Oct 23 15:14:54 +0000 2024,0,normal,@iteramfs Gk usah kkn nder nanti rame2 bilang ...,1.860000e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

HAPUS ATRIBUT

In [ ]:
columns_to_drop = ['conversation_id_str','image_url','favorite_count','id_str',
                   'location','image_url','in_reply_to_screen_name','lang',
                   'quote_count','reply_count','retweet_count','tweet_url',
                   'user_id_str','created_at','username']
df = df_combined.drop(columns=columns_to_drop, errors='ignore')

In [ ]:
df.shape

(10, 2)

In [ ]:
df

        label                                          full_text
0     depresi                   aku sedih pdhl lg pgn di support
1      normal  @muh_basra Keknya beban depresi pada cash for ...
2     depresi  gue udah di titik cape banget nutup nutupin im...
3     depresi  Kadang pengen gw ledakin tapi takut ada yg nyi...
4      normal  Rasa bersalah juga kalau jumpa mashayikh tak c...
4995  depresi  Hari demi hari makin di bikin takut buat ngela...
4996  depresi  nyerah aja kali ya beneran capek sm kehidupan ...
4997   normal  @diddekarisma Udah nyerah sama hidup tuh makan...
4998  depresi  udah di tahap nyerah sm diri sendiri nyoba bua...
4999   normal  @iteramfs Gk usah kkn nder nanti rame2 bilang ...

CASE FOLDING

In [ ]:
df['full_text'] = df['full_text'].str.lower()
df

        label                                          full_text
0     depresi                   aku sedih pdhl lg pgn di support
1      normal  @muh_basra keknya beban depresi pada cash for ...
2     depresi  gue udah di titik cape banget nutup nutupin im...
3     depresi  kadang pengen gw ledakin tapi takut ada yg nyi...
4      normal  rasa bersalah juga kalau jumpa mashayikh tak c...
4995  depresi  hari demi hari makin di bikin takut buat ngela...
4996  depresi  nyerah aja kali ya beneran capek sm kehidupan ...
4997   normal  @diddekarisma udah nyerah sama hidup tuh makan...
4998  depresi  udah di tahap nyerah sm diri sendiri nyoba bua...
4999   normal  @iteramfs gk usah kkn nder nanti rame2 bilang ...

CLEANING

In [ ]:
df = df.drop_duplicates(subset=['full_text'])
df.duplicated().sum()

In [ ]:
def clean_text(text):
    # Menghapus mention
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)
    # Menghapus hashtag
    text = re.sub(r'#', '', text)
    # Menghapus link
    text = re.sub(r'http[s]?://\S+', '', text)
    # Menghapus karakter non-alfanumerik
    text = re.sub(r'[^A-Za-z0-9\s]', '', text)
    # Menghapus spasi berlebihan
    text = re.sub(r'\s+', ' ', text).strip()
    # mengubah emoji menjadi text
    text = emoji.demojize(text)
    # mengubah tanda baca berulang menjadi tunggal
    text = re.sub(r'([^\w\s])\1+', r'\1', text)

    return text

df['full_text'] = df['full_text'].apply(clean_text)
df

        label                                          full_text
0     depresi                   aku sedih pdhl lg pgn di support
1      normal  keknya beban depresi pada cash for healing ga ...
2     depresi  gue udah di titik cape banget nutup nutupin im...
3     depresi  kadang pengen gw ledakin tapi takut ada yg nyi...
4      normal  rasa bersalah juga kalau jumpa mashayikh tak c...
4995  depresi  hari demi hari makin di bikin takut buat ngela...
4996  depresi  nyerah aja kali ya beneran capek sm kehidupan ...
4997   normal  udah nyerah sama hidup tuh makanya nyemplungin...
4998  depresi  udah di tahap nyerah sm diri sendiri nyoba bua...
4999   normal  gk usah kkn nder nanti rame2 bilang yg salah p...

In [ ]:
df.to_csv('/content/drive/MyDrive/SKRIPSI/New/10_prepo_dep.csv', index=False)

NORMALIZATION

In [ ]:
import csv
import string
import pandas as pd
import re

In [ ]:
import requests

url = "https://github.com/nasalsabila/kamus-alay/blob/master/colloquial-indonesian-lexicon.csv"

response = requests.get(url)
if response.status_code == 200:
    print("File berhasil diakses!")
    print(response.text[:500])  # Cek sebagian isi file
else:
    print("Gagal mengakses file. Error:", response.status_code)

File berhasil diakses!






<!DOCTYPE html>
<html
  lang="en"

  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"

  >



  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.gi

In [ ]:
# URL file CSV di GitHub (RAW)
url = "https://raw.githubusercontent.com/nasalsabila/kamus-alay/master/colloquial-indonesian-lexicon.csv"

# Membaca CSV dengan delimiter koma (",") atau sesuaikan dengan file
slang_df = pd.read_csv(url, delimiter=",", header=None)

# Ambil kolom pertama sebagai daftar slang-formal
slang_list = slang_df.iloc[:, 0].tolist()

# Cek 10 kata pertama dari daftar stopword
print(slang_list[:10])

['slang', 'woww', 'aminn', 'met', 'netaas', 'keberpa', 'eeeehhhh', 'kata2nyaaa', 'hallo', 'kaka']

In [ ]:
try:
    #Baca CSV dengan delimiter otomatis
    slang_df = pd.read_csv(url, sep=None, engine='python')

    #Cek apakah CSV memiliki 2 kolom
    if slang_df.shape[1] < 2:
        raise ValueError("File CSV tidak memiliki dua kolom untuk normalisasi!")

    #Buat dictionary slang jadi formal
    norm_dict = dict(zip(slang_df.iloc[:, 0], slang_df.iloc[:, 1]))

    #Fungsi normalisasi menggunakan regex
    def normalisasi(str_text):
        words = str_text.split()  # Pecah kalimat jadi list kata
        words = [norm_dict.get(word, word) for word in words]
        return " ".join(words)  # Gabungkan kembali jadi kalimat

    #Baca file dataset lokal
    file_lokal = "/content/drive/MyDrive/SKRIPSI/New/10_prepo_dep.csv"
    df = pd.read_csv(file_lokal)

    #Pastikan kolom 'full_text' ada
    if 'full_text' not in df.columns:
        raise ValueError("Kolom 'full_text' tidak ditemukan dalam file lokal!")

    #Terapkan normalisasi
    df['full_text'] = df['full_text'].astype(str).apply(normalisasi)

except Exception as e:
    print(f"Terjadi error: {e}")

In [ ]:
df

     label                                          full_text
0  depresi           aku sedih padahal lagi pengin di support
1   normal  kayaknya beban depresi pada cash for healing e...
2  depresi  gue sudah di titik capek banget nutup menutupi...
3  depresi  kadang pengin gue ledakin tapi takut ada yang ...
4   normal  rasa bersalah juga kalau jumpa mashayikh tak c...
5  depresi  hari demi hari makin di bikin takut buat ngela...
6  depresi  nyerah saja kali ya benaran capek sama kehidup...
7   normal  sudah nyerah sama hidup tuh makanya nyemplungi...
8  depresi  sudah di tahap nyerah sama diri sendiri mencob...
9   normal  enggak usah kkn nder nanti rame-rame bilang ya...

STOPWORD REMOVAL

In [ ]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 12.3 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import (
    StopWordRemoverFactory, StopWordRemover, ArrayDictionary
)

# Stopword tambahan
more_stopword = ['tuh','lah','kok','sok','cs','sih','loh','nih']

# Buat daftar stopword menggunakan Sastrawi dan tambahkan stopword tambahan
stopwords = StopWordRemoverFactory().get_stop_words()
stopwords.extend(more_stopword)

# Inisialisasi StopWordRemover dengan daftar stopword yang diperbarui
new_array = ArrayDictionary(stopwords)
stopwords_remover = StopWordRemover(new_array)

# Fungsi untuk menghapus stopword
def remove_stopwords(text):
    return stopwords_remover.remove(text)

df['full_text'] = df['full_text'].apply(remove_stopwords)
df

     label                                          full_text
0  depresi                   aku sedih padahal pengin support
1   normal  kayaknya beban depresi cash for healing enggak...
2  depresi  gue titik capek banget nutup menutupi image ke...
3  depresi  kadang pengin gue ledakin takut yang nyiksa di...
4   normal  rasa bersalah kalau jumpa mashayikh tak cuba k...
5  depresi  hari hari makin bikin takut buat ngelanjutin h...
6  depresi  nyerah kali benaran capek sama kehidupan capek...
7   normal  nyerah sama hidup makanya nyemplungin diri minyak
8  depresi  di tahap nyerah sama diri sendiri mencoba buat...
9   normal  enggak usah kkn nder rame-rame bilang salah pa...

CONVERT VALUE

In [ ]:
df['label'] = df['label'].astype(str).str.strip().str.lower()
print(df['label'].unique())  # pastikan label hanya "depresi" dan "normal"

['depresi' 'normal']

In [ ]:
df['label'] = df['label'].map({"depresi": 1, "normal": 0})

In [ ]:
print(df['label'].isnull().sum())

0

In [ ]:
df

   label                                          full_text
0      1                   aku sedih padahal pengin support
1      0  kayaknya beban depresi cash for healing enggak...
2      1  gue titik capek banget nutup menutupi image ke...
3      1  kadang pengin gue ledakin takut yang nyiksa di...
4      0  rasa bersalah kalau jumpa mashayikh tak cuba k...
5      1  hari hari makin bikin takut buat ngelanjutin h...
6      1  nyerah kali benaran capek sama kehidupan capek...
7      0  nyerah sama hidup makanya nyemplungin diri minyak
8      1  di tahap nyerah sama diri sendiri mencoba buat...
9      0  enggak usah kkn nder rame-rame bilang salah pa...